# Configuração original (mantenha)
[supabase]
url = "https://xtsrfcjdihcrcmdsbkli.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0c3JmY2pkaWhjcmNtZHNia2xpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNjE3MTMwMCwiZXhwIjoyMDUxNzQ3MzAwfQ.nHk5iYGrGCybALtO83Yi__1Ku7GC70nJryf8TG2MvtM"

# Adicione estas linhas (MAIÚSCULAS - necessário para st_login_form)
SUPABASE_URL = "https://xtsrfcjdihcrcmdsbkli.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0c3JmY2pkaWhjcmNtZHNia2xpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNjE3MTMwMCwiZXhwIjoyMDUxNzQ3MzAwfQ.nHk5iYGrGCybALtO83Yi__1Ku7GC70nJryf8TG2MvtM"