# Configuração original (mantenha)
[supabase]
url = "your_supbase_credentials"
key = "your_supbase_credentials"

# Adicione estas linhas (MAIÚSCULAS - necessário para st_login_form)
SUPABASE_URL = "your_supbase_credentials"
SUPABASE_KEY = "your_supbase_credentials"
